### ISSUE TITLE
9g) Lag en funksjon som skriver ut ei liste med avtaler.

### ISSUE THREAD

**Issue by wathne** [wathne/dat120-22h-g94#8]
9g) Lag en funksjon som skriver ut ei liste med avtaler til skjermen. Funksjonen skal minimum
skrive ut indeksen til avtalen i lista og tittel til avtalen. Den kan alternativt skrive ut indeksen
til avtalen og så hele avtalen som definert i (Underscore)(Underscore)__str__(Underscore)(Underscore) metoden. Funksjonen skal ha en frivillig
parameter «overskrift» som skal være en overskrift som funksjonen skriver ut før avtalene i
lista. Funksjonen skal inkludere indeksen til hver avtale i utskriften.

**Comment by Johnny78i** [comment]
La også til en for loop som lager en liste med 24 avtaler

**Comment by wathne** [comment]
Jeg er ferdig med denne deloppgaven.
Fil: asdf.py
